# Use Node.js LTS version
FROM node:lts

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install


# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start the app
CMD [ "npm", "start" ]
